config/routes.rb
Buzurg::Application.routes.draw do
  
  devise_for :users

  root :to => "home#index"

  get '/howitworks', to: 'page#howitworks', as: 'howitworks'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end
	
end		

app/controllers/page_controller.rb
class PageController < ApplicationController

	def howitworks

	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def active(page)
  		return 'class="active"'.html_safe if current_page?(page)
  	end
  	
end

app/views/home/index.html.erb
home

<button type="button" class="btn btn-ttc">Save changes</button>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :class => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#template-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><%= Buzurg::Application::APPLICATION_TITLE %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="template-navbar-collapse">
    <ul class="nav navbar-nav">
      <li <%= active(root_path) %> ><%= link_to "Home", root_path %></li>
      <li <%= active(howitworks_path) %> ><%= link_to "How It Works", howitworks_path %></li>
      
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
            <li class="navbar-text">coins <span class="badge">0</span></li>
            <li><%= link_to "Not you? Sign out", destroy_user_session_path, :method => :delete, id: "sign_out" %></li>
        <% else %>
            <li <%= active(new_user_session_path) %> ><%= link_to "Sign In", new_user_session_path %></li>
            <li <%= active(new_user_registration_path) %> ><%= link_to "Sign Up", new_user_registration_path, id: "sign_up" %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">-->
    <title><%= content_for?(:title) ? yield(:title) : Buzurg::Application::APPLICATION_TITLE %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Buzurg::Application::APPLICATION_TITLE %>"
    <meta name="author" content="">
    
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

  </head>
  <body>
    <header>
        <%= render 'layouts/navigation' %>
    </header>

    <div id="main" role="main">
        <div class="container">
            <%= render 'layouts/messages' %>
            <%= yield %>
        
            <footer>
              <br/>
              &copy; <a href='http://raffles.in'><%= Buzurg::Application::APPLICATION_TITLE %></a> <%= Time.now.year %>
            </footer>
        </div> <!-- End of container -->
     
    </div> <!--! end of #main -->
  </body>
</html>

app/views/page/howitworks.html.erb
how it works

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>